### ISSUE TITLE
Config to disable mobs spawning with the swords

### ISSUE THREAD

**Issue by SandwichHorror** [Darkhax-Minecraft/More-Swords-Legacy#7]
Could you please add a config to disable zombies and skeletons spawning with the sword relics? We have these as very powerful items in Rebirth of the Night, and despite using LootTweaker to supposedly remove them from loot tables, they still show up wielded by the mobs and still drop. It's super broken for balance. We have been trying to solve this for a long time and would greatly appreciate this option so we don't have to find another legendary sword mod!

**Comment by CalaMariGold** [comment]
Yeah, we desperately need this feature.

**Comment by Darkhax** [comment]
Thank you for explaining the issue. I can add support for this config option soon.

**Comment by Darkhax** [comment]
There are now two new config options in the general section. One is for the spawn chance of this happening, and the other is for whether or not relics are allowed. 

The reason loot tweaker could not help is because zombie equipment is not a loot table. For example you can throw a sword on the ground and the zombie can pick up your sword.
